%macro run_all_cahps(quota_name); 

				%let QuotaVariable  =  &quota_name;
				%put &QuotaVariable; 
				%let Suffix	=  _&quota_name;
				%include "K:\TX-EQRO\Research\Member_Surveys\THLC\STARPLUS_2023\sp_cahps.sas" ;
%mend run_all_cahps; 

%run_all_cahps(quota_01); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_02); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_03); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_04); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_05);
	proc datasets library = work kill nolist; 
	run; 
	quit;  
%run_all_cahps(quota_06); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_07); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_08); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_09); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_10); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_11); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_12); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_13); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_14); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_15); 
	proc datasets library = work kill nolist; 
	run; 
	quit; 
%run_all_cahps(quota_16); 
* %run_all_cahps(PHI_Plan_Code); 
* %run_all_cahps(PHI_SA_Name); 
* %run_all_cahps(PHI_Plan_Name); 
