OPTIONS PS=MAX FORMCHAR="|----|+|---+=|-/\<>*" MPRINT nofmterr;

%let Full_Path_And_File_Name 	= K:\TX-EQRO\Research\Member_Surveys\THLC\STARChild_2023\updater_for_wrong_format\case_mix_output\gnr\df_format_all_quota_sc_gnr.sas7bdat;
%let QuotaVariable 			 			  =  &quota_name;
%let Suffix					 			  =  _&quota_name;
%let OutputFolder 			 			  =  K:\TX-EQRO\Research\Member_Surveys\THLC\STARChild_2023\SC_output_thlc\case_mix_output\gnr\after_ICHP9_change\;
%let pvalue = 0.05; 
%let adjuster = rage health_exc health_vgd health_gd health_fair health_poor edu_8th edu_somehs edu_hs edu_somecoll edu_collgrad edu_morecoll; 
%let wgtmean         = CompWeight; 
%let low_denominator = 3; 

%include "K:/TX-EQRO/Research/Member_Surveys/Syntax/SAS/Macro_cahps50_launcher.sas" ;


%cahps(name=AtC, outname=AtC, var=cahps4 cahps6 cahps10 cahps41, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=GCQ, outname=GCQ, var=cahps4 cahps6, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=GNC, outname=GNC, var=cahps10 cahps41, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=HWDC, outname=HWDC, var=cahps27 cahps28 cahps29 cahps31 cahps32, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps9, outname=out_cahps9, var=cahps9, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps36, outname=out_cahps36, var=cahps36, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps43, outname=out_cahps43, var=cahps43, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps49, outname=out_cahps49, var=cahps49, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps35, outname=out_cahps35, var=cahps35, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=Custserv, outname=Custserv, var=cahps45 cahps46, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps48, outname=out_cahps48, var=cahps48, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps4, outname=out_cahps4, var=cahps4, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps6, outname=out_cahps6, var=cahps6, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps10, outname=out_cahps10, var=cahps10, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps41, outname=out_cahps41, var=cahps41, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS3, outname=out_CAHPS3, var=CAHPS3, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS4, outname=out_CAHPS4, var=CAHPS4, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS5, outname=out_CAHPS5, var=CAHPS5, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS6, outname=out_CAHPS6, var=CAHPS6, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_AR1, outname=out_AR1, var=AR1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_AR2, outname=out_AR2, var=AR2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_UT1, outname=out_UT1, var=UT1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_ICHP2, outname=out_ICHP2, var=ICHP2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_ICHP3, outname=out_ICHP3, var=ICHP3, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS7, outname=out_CAHPS7, var=CAHPS7, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS8, outname=out_CAHPS8, var=CAHPS8, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS9, outname=out_CAHPS9, var=CAHPS9, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_AH1, outname=out_AH1, var=AH1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_AH2, outname=out_AH2, var=AH2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS10, outname=out_CAHPS10, var=CAHPS10, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS11, outname=out_CAHPS11, var=CAHPS11, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS12, outname=out_CAHPS12, var=CAHPS12, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_FREW1, outname=out_FREW1, var=FREW1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_FREW4, outname=out_FREW4, var=FREW4, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS14, outname=out_CAHPS14, var=CAHPS14, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS16, outname=out_CAHPS16, var=CAHPS16, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS17, outname=out_CAHPS17, var=CAHPS17, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS18, outname=out_CAHPS18, var=CAHPS18, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS19, outname=out_CAHPS19, var=CAHPS19, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS20, outname=out_CAHPS20, var=CAHPS20, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS21, outname=out_CAHPS21, var=CAHPS21, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS22, outname=out_CAHPS22, var=CAHPS22, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS23, outname=out_CAHPS23, var=CAHPS23, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS25, outname=out_CAHPS25, var=CAHPS25, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS26, outname=out_CAHPS26, var=CAHPS26, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS27, outname=out_CAHPS27, var=CAHPS27, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_C1, outname=out_C1, var=C1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS28, outname=out_CAHPS28, var=CAHPS28, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS29, outname=out_CAHPS29, var=CAHPS29, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS30, outname=out_CAHPS30, var=CAHPS30, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS31, outname=out_CAHPS31, var=CAHPS31, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_C2, outname=out_C2, var=C2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS32, outname=out_CAHPS32, var=CAHPS32, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CU14, outname=out_CU14, var=CU14, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CU15, outname=out_CU15, var=CU15, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CU23, outname=out_CU23, var=CU23, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CU24, outname=out_CU24, var=CU24, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS34, outname=out_CAHPS34, var=CAHPS34, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS35, outname=out_CAHPS35, var=CAHPS35, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS36, outname=out_CAHPS36, var=CAHPS36, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_PD1, outname=out_PD1, var=PD1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_PD2, outname=out_PD2, var=PD2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS37, outname=out_CAHPS37, var=CAHPS37, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS40, outname=out_CAHPS40, var=CAHPS40, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS41, outname=out_CAHPS41, var=CAHPS41, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS42, outname=out_CAHPS42, var=CAHPS42, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS43, outname=out_CAHPS43, var=CAHPS43, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_ICHP4, outname=out_ICHP4, var=ICHP4, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_ICHP9, outname=out_ICHP9, var=ICHP9, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS44, outname=out_CAHPS44, var=CAHPS44, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS45, outname=out_CAHPS45, var=CAHPS45, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS46, outname=out_CAHPS46, var=CAHPS46, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS47, outname=out_CAHPS47, var=CAHPS47, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS48, outname=out_CAHPS48, var=CAHPS48, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS49, outname=out_CAHPS49, var=CAHPS49, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_T1, outname=out_T1, var=T1, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_T2, outname=out_T2, var=T2, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_T3, outname=out_T3, var=T3, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS50, outname=out_CAHPS50, var=CAHPS50, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS51, outname=out_CAHPS51, var=CAHPS51, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS52, outname=out_CAHPS52, var=CAHPS52, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS53, outname=out_CAHPS53, var=CAHPS53, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS54, outname=out_CAHPS54, var=CAHPS54, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS55, outname=out_CAHPS55, var=CAHPS55, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS56, outname=out_CAHPS56, var=CAHPS56, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS57, outname=out_CAHPS57, var=CAHPS57, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS58, outname=out_CAHPS58, var=CAHPS58, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS59, outname=out_CAHPS59, var=CAHPS59, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS60, outname=out_CAHPS60, var=CAHPS60, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS61, outname=out_CAHPS61, var=CAHPS61, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS62, outname=out_CAHPS62, var=CAHPS62, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS63, outname=out_CAHPS63, var=CAHPS63, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS64, outname=out_CAHPS64, var=CAHPS64, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS65, outname=out_CAHPS65, var=CAHPS65, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS66, outname=out_CAHPS66, var=CAHPS66, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS67, outname=out_CAHPS67, var=CAHPS67, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS68, outname=out_CAHPS68, var=CAHPS68, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_TRTCHLD, outname=out_TRTCHLD, var=TRTCHLD, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_TRTADLT, outname=out_TRTADLT, var=TRTADLT, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_chngage, outname=out_chngage, var=chngage, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_CAHPS75, outname=out_CAHPS75, var=CAHPS75, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps8, outname=out_cahps8, var=cahps8, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=CoC_CCC, outname=CoC_CCC, var=cahps13 cahps24, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=GSS, outname=GSS, var=cahps15 cahps18 cahps21, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=FCCPD, outname=FCCPD, var=cahps33 cahps38 cahps39, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps51, outname=out_cahps51, var=cahps51, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps16, outname=out_cahps16, var=cahps16, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps19, outname=out_cahps19, var=cahps19, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps22, outname=out_cahps22, var=cahps22, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps52, outname=out_cahps52, var=cahps52, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps13, outname=out_cahps13, var=cahps13, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps15, outname=out_cahps15, var=cahps15, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps24, outname=out_cahps24, var=cahps24, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps33, outname=out_cahps33, var=cahps33, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps38, outname=out_cahps38, var=cahps38, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps39, outname=out_cahps39, var=cahps39, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps18, outname=out_cahps18, var=cahps18, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_cahps21, outname=out_cahps21, var=cahps21, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_needmeds, outname=out_needmeds, var=needmeds, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_needserv, outname=out_needserv, var=needserv, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_limited, outname=out_limited, var=limited, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_needther, outname=out_needther, var=needther, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_needcoun, outname=out_needcoun, var=needcoun, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_specialneed, outname=out_specialneed, var=specialneed, pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1);
%cahps(name=out_trtadlt, outname=out_trtadlt, var=trtadlt,pvalue = &pvalue, wgtmean = &wgtmean, wgtdata = , low_denominator = &low_denominator, adjuster = &adjuster, excludeQuotas = , recode = 0, vartype = 1); 